services:
  gateway:
    image: kcollins/ignition:8.1.3
    restart: unless-stopped    
    networks:
      - proxy
      - db
    volumes:
      #- ./gw-init/gateway.gwbk
      - gateway-data:/var/lib/ignition/data
      - ./redminelib:/var/lib/ignition/user-lib/pylib/site-packages/redminelib
    env_file:
      - secrets/ignitionsecrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.rule=Host(`${MY_DOMAIN}`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=8088"
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.http.middlewares.gateway-replacepathmain.replacepathregex.regex=^/main/StatusPing$$"
      - "traefik.http.middlewares.gateway-replacepathmain.replacepathregex.replacement=/StatusPing"
      - "traefik.http.routers.gateway.middlewares=gateway-replacepathmain"

  redmine:
    build:
      context: redmine-build
    restart: unless-stopped 
    volumes:
      - ./redmine-files:/usr/src/redmine/files
      - ./redmine-plugins:/usr/src/redmine/plugins
      - ./config/production.rb:/usr/src/redmine/config/environments/production.rb
      - ./config/environment.rb:/usr/src/redmine/config/environment.rb
      - ./config/config.ru:/usr/src/redmine/config.ru
    networks:
      - db
      - proxy
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redmine.entrypoints=websecure"
      - "traefik.http.routers.redmine.rule=Host(`${MY_DOMAIN}`) && (PathPrefix(`/redmine/`) || Path(`/redmine`) )"
      - "traefik.http.services.redmine.loadbalancer.server.port=3000"
      - "traefik.http.routers.redmine.tls.certresolver=myresolver"

    env_file:
      - ./secrets/redmine.env
    ports:
      - 3000:3000

  db:
    build:
      context: db-build
    restart: unless-stopped 
    networks:
      - db
    volumes:
      - db-data:/var/lib/mysql
      - ./secrets/extra.cnf:/root/.my.cnf
      - ./db-init:/docker-entrypoint-initdb.d
      - ./db-backups:/backups
    env_file:
      - ./secrets/db.env
    environment:
      RETAIN_FILES_COUNT: 5
  prune:
    build:
      context: prune-build
    networks:
      - db
  nodered:
    restart: always
    image: nodered/node-red:latest
    ports: 
      - 1880:1880
    volumes:
      - datanodered:/data
    networks:
      - db
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.routers.nodered.rule=Host(`${MY_DOMAIN}`) && (PathPrefix(`/redmine/`) || Path(`/redmine`)) && Headers(`nodered`,`yes`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.http.routers.nodered.tls.certresolver=myresolver"
networks:
  db:
  proxy:
    external: true
    name: proxy

volumes:
  db-data:
  gateway-data:
  datanodered: