# Launch with:
#  $ docker-compose -f stack-proxy.yml -p proxy up -d
---
x-log-opts:
  &log-opts
  logging:
    driver: "json-file"
    options:
      max-size: "200k"
      max-file: "10"

services:
  proxy:
    <<: *log-opts
    image: traefik:2.4
    container_name: proxy
    restart: always
    environment:  # https://docs.traefik.io/reference/static-configuration/env/
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=proxy
    ports:
      - 80:80
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.entrypoint=web"
      - "traefik.http.routers.proxy.rule=Host(`proxy.vcap.me`)"
      - "traefik.http.routers.proxy.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    name: proxy
